package main

import (
	"net/http"

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "github.com/adrian-sturm/swaggo-test/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title       Swaggo Example API
// @version     1.0
// @description This is an example

// @license.name Apache 2.0
// @license.url  http://www.apache.org/licenses/LICENSE-2.0.html

// @securityDefinitions.apikey ApiKeyAuth
// @in                         header
// @name                       Bearer
// @description                Accesskey based security scheme to secure api

// @host     localhost:8080
// @BasePath /v2
func main() {
	e := echo.New()

	e.GET("/v2/ping", pong)
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":8080"))
}

// Pong godoc
// @Summary     Pong.
// @Description pong!
// @Accept      json
// @Produce     json
// @Success     200 {object} string
// @Failure     404 {object} string
// @Failure     500 {object} string
// @Router      /v2/pong [get]
// @Security    ApiKeyAuth
func pong(c echo.Context) error {
	return c.String(http.StatusOK, "Pong")
}
